image: /home/mimi/test_ws/src/happymimi_apps/happymimi_navigation/maps/training_area.pgm
resolution: 0.050000
origin: [-10.000000, -10.000000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

